-- Database Schema Updates for User Tracking
-- Run this in your Supabase SQL Editor

-- Drop existing table and recreate with all required columns
DROP TABLE IF EXISTS annotations;

-- Create the new table with all required columns including user tracking
CREATE TABLE annotations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id INT NOT NULL,
  reasoning_category TEXT,           -- Type of reasoning (Logical, Mathematical, etc.)
  cultural_aspect TEXT,             -- Cultural domain (Food, Music, Politics, etc.)
  original_template TEXT,
  values JSONB NOT NULL,
  
  -- Generated content
  generated_question TEXT NOT NULL,
  generated_option1 TEXT NOT NULL,  -- Option A (correct answer)
  generated_option2 TEXT NOT NULL,  -- Option B
  generated_option3 TEXT NOT NULL,  -- Option C
  generated_option4 TEXT NOT NULL,  -- Option D
  
  -- Translated content
  translated_question TEXT NOT NULL,
  translated_option1 TEXT NOT NULL,  -- Translation of Option A
  translated_option2 TEXT NOT NULL,  -- Translation of Option B
  translated_option3 TEXT NOT NULL,  -- Translation of Option C
  translated_option4 TEXT NOT NULL,  -- Translation of Option D
  
  -- User tracking columns
  user_id TEXT NOT NULL,              -- dev_xxx or Prolific ID
  device_fingerprint TEXT NOT NULL,   -- FingerprintJS ID
  user_ip TEXT,                      -- IP address from request
  is_prolific_user BOOLEAN DEFAULT FALSE,  -- TRUE for Prolific users
  
  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  language TEXT          -- Optional: to track which language the translation is in
);

-- Add indexes for performance
CREATE INDEX idx_annotations_template_id ON annotations(template_id);
CREATE INDEX idx_annotations_created_at ON annotations(created_at);
CREATE INDEX idx_annotations_reasoning_category ON annotations(reasoning_category);
CREATE INDEX idx_annotations_cultural_aspect ON annotations(cultural_aspect);

-- Add user tracking indexes for fast queries
CREATE INDEX idx_annotations_user_id ON annotations(user_id);
CREATE INDEX idx_annotations_device_fingerprint ON annotations(device_fingerprint);
CREATE INDEX idx_annotations_user_fingerprint ON annotations(user_id, device_fingerprint);
CREATE INDEX idx_annotations_is_prolific ON annotations(is_prolific_user);
CREATE INDEX idx_annotations_user_ip ON annotations(user_ip);

-- Add comments to document the fields
COMMENT ON COLUMN annotations.reasoning_category IS 'The type of reasoning required (e.g., Logical Reasoning, Mathematical Reasoning, Multi-hop Reasoning, etc.)';
COMMENT ON COLUMN annotations.cultural_aspect IS 'The cultural domain being tested (e.g., Food and Cuisine, Music and Art, Politics and Governance, etc.)';

-- View the table structure
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns 
WHERE table_name = 'annotations' 
ORDER BY ordinal_position;

-- Verify the indexes were created
SELECT indexname, indexdef 
FROM pg_indexes 
WHERE tablename = 'annotations' 
AND indexname LIKE 'idx_annotations_%';
